name: extractor
description: Create direct video links from various websites like youtube, vimeo and many more
version: 0.0.2
homepage: https://github.com/ashishpipaliya/extractor

environment:
  sdk: ">=2.16.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  html: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
